### ISSUE TITLE
Hey i am getting this error "Warning: fetchStandardFontData: failed to fetch file "LiberationSans-Bold.ttf" is there way how i can fix this??

### ISSUE THREAD

**Issue by sujjeee** [Luluno01/pdfjs-dist-import-reproducer#1]
Hey there,

I noticed your previous conversations regarding this issue, so I thought I'd ask if you could help me with it. Basically, I'm encountering this error and I don't know how to fix it:

## Warning: fetchStandardFontData: failed to fetch file "LiberationSans-Regular.ttf" with "UnknownErrorException: The standard font "baseUrl" parameter must be specified, ensure that the "standardFontDataUrl" API parameter is provided.".

Please help me if you know how to deal with this.

**Comment by Luluno01** [comment]
I haven't been tackling PDF.js for a while but I do remember there is such a warning. I didn't fix it because it's a warning and I don't use PDF.js to render anything. If you don't really need to render the PDF, you can ignore this warning, too. But if you need to, the warning message indicates that you have to specify a parameter which tells PDF.js where "standard fonts" are, as explained by [react-pdf](https://github.com/wojtekmaj/react-pdf/blob/main/packages/react-pdf/README.md#support-for-standard-fonts).

Here is another issue under PDF.js for your reference: https://github.com/mozilla/pdf.js/issues/4244

**Comment by sujjeee** [comment]
Thanks for the reply!!

By the way, I tried to provide the path for the standard font, but I'm still encountering the same error. My terminal is filled with the same error message.

This is how I'm providing the path:

```bash
const pdf = await getDocument({
  data: uint8Array,
  standardFontDataUrl:
    "{....}/node_modules/pdfjs-dist/standard_fonts"
}).promise;
```

However, I still don't know why I'm getting the error.

**Comment by Luluno01** [comment]
> Thanks for the reply!!
> 
> By the way, I tried to provide the path for the standard font, but I'm still encountering the same error. My terminal is filled with the same error message.
> 
> This is how I'm providing the path:
> 
> ```shell
> const pdf = await getDocument({
>   data: uint8Array,
>   standardFontDataUrl:
>     "{....}/node_modules/pdfjs-dist/standard_fonts"
> }).promise;
> ```
> 
> However, I still don't know why I'm getting the error.

The error message should be a bit different after you provide `standardFontDataUrl`. Could you post the error message you got after setting `standardFontDataUrl`?

Also, if you plan to run PDF.js in a browser, you need to fill in `standardFontDataUrl` with the base URL where `standard_fonts` can be fetched by an HTTP request sent from the browser. For example, you can firstly make sure `standard_fonts/*` are served as static assets. You can achieve this by copying `standard_fonts` folder to the `assets` folder. Then, set `standardFontDataUrl` to `'/standard_fonts'` (which points to the `assets/standard_fonts` folder). It should, hopefully, be used to construct full URLs to the fonts that are served from your static assets folder.

Otherwise, if you plan to run PDF.js in serverless function, you probably need to figure out how to make Webpack copy the entire `standard_fonts` folder to the build output so that `standardFontDataUrl` points to a folder that actually exists at runtime. The precise configuration, unfortunately, is not known to me as I'm not familiar with Webpack stuff (it's annoying, huh? XD). So, you may need to search through the documentations of both Next.js and Webpack. Make sure you are looking into the right version of documentation that matches the Webpack version you are using. You can also open an issue in the PDF.js repo or Next.js repo to seek for more help.

**Comment by sujjeee** [comment]
Okay, so I'm using pdfjs-dist in Node.js to obtain the dimensions of the given text and perform some actions on it. In simple terms, I need to extract the text from each page of the PDF.
 
```bash
import { getDocument } from "pdfjs-dist";

const uint8Array = new Uint8Array(response);

const pdf = await getDocument({
  data: uint8Array,
  standardFontDataUrl:
    "D:/PDFScribe/nodejs/node_modules/pdfjs-dist/standard_fonts"
}).promise;
```

And speaking about my terminal being filled with warnings, I mean it! Look at this image XD.
![Screenshot 2024-02-09 114836](https://github.com/Luluno01/pdfjs-dist-import-reproducer/assets/101963203/4c5da8e5-18e1-4c29-a157-35ed7e2acf07)


The code is working fine, it's just this warning that's annoying me a lot!

**Comment by Luluno01** [comment]
> Okay, so I'm using pdfjs-dist in Node.js to obtain the dimensions of the given text and perform some actions on it. In simple terms, I need to extract the text from each page of the PDF.
> 
> ```shell
> import { getDocument } from "pdfjs-dist";
> 
> const uint8Array = new Uint8Array(response);
> 
> const pdf = await getDocument({
>   data: uint8Array,
>   standardFontDataUrl:
>     "D:/PDFScribe/nodejs/node_modules/pdfjs-dist/standard_fonts"
> }).promise;
> ```
> 
> And speaking about my terminal being filled with warnings, I mean it! Look at this image XD. ![Screenshot 2024-02-09 114836](https://private-user-images.githubusercontent.com/101963203/303568522-4c5da8e5-18e1-4c29-a157-35ed7e2acf07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NjU3NzYsIm5iZiI6MTcwNzQ2NTQ3NiwicGF0aCI6Ii8xMDE5NjMyMDMvMzAzNTY4NTIyLTRjNWRhOGU1LTE4ZTEtNGMyOS1hMTU3LTM1ZWQ3ZTJhY2YwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQwNzU3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2MwMWJiMzc2ZTkwZTUyYjBjNTJiMjBiY2I2OTFmNWFhM2U1ZGRiZWYwNDAxYjI4YmQ1YmM4ZjNiYjUxODYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zdnDREmWgQJ_sDFE7ghvu3BizAkbn4uurEHcPikmvQA)
> 
> The code is working fine, it's just this warning that's annoying me a lot!

End `standardFontDataUrl` with a trailing slash and it should fix it. Notice that in the warning message, the paths where PDF.js wants to load fonts from are constructed from `standardFontDataUrl` directly without adding a slash.

**Comment by sujjeee** [comment]
@Luluno01 Reallyyy, thank you so much, man!! 

I was just so frustrated with that warning, and the issue was just this --> '/ '
Thanks again for helping; it's fixed now.

**Comment by lirantal** [comment]
Another clean and easy way to do it in Node.js is as follows:

```js
import path from "node:path";

const pdfDocument = await pdfjsLib.getDocument({
  data: pdfDataArray,
  standardFontDataUrl: path.join(
    import.meta.dirname,
    "node_modules/pdfjs-dist/standard_fonts/"
  ),
}).promise;
```

**Comment by Echron** [comment]
@lirantal this works, however the trailing slash gets removed in the join so I had to add `+ '/'` after the .join:


```
import path from "node:path";

const pdfDocument = await pdfjsLib.getDocument({
  data: pdfDataArray,
  standardFontDataUrl: path.join(
    import.meta.dirname,
    "node_modules/pdfjs-dist/standard_fonts/"
  ) + '/',
}).promise;
```

**Comment by lirantal** [comment]
@Echron glad to hear!
You can also use `path.sep` (Node.js built-in) for an OS-specific directory separator.
